name: tieba_image_parser
description: 'Parse original images from threads in Tieba.'
publish_to: 'none'
version: 0.1.0

environment:
    sdk: ^3.6.0

dependencies:
    flutter:
        sdk: flutter
    http: ^1.2.2
    html: ^0.15.5
    gal: ^2.3.1
    mime: ^2.0.0
    path_provider: ^2.1.5
    provider: ^6.1.2
    url_launcher: ^6.3.1
    package_info_plus: ^8.1.2
    # shared_preferences: ^2.3.5

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^5.0.0

flutter:
    uses-material-design: true

    assets:
        - assets/icon_github.png
        - assets/icon_qq.png
        - assets/avatar.jpg
